version: "3.1"
services:
    mysql:
        image: mysql:5.7
        container_name: plainpad-database
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=plainpad
        ports:
            - "8001:3306"
    server:
        build: ./server
        image: plainpad-server:v1
        container_name: plainpad-server
        ports:
            - "8000:80"
        volumes:
            - ../server:/var/www/html
            - ./server/php.ini:/usr/local/etc/php/conf.d/99-overrides.ini
